# Generated by Django 5.2 on 2025-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ac_role",
            field=models.IntegerField(
                choices=[(0, "User"), (1, "Organizations")], default=0
            ),
        ),
    ]
