# Generated by Django 5.2 on 2025-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ac_role",
            field=models.IntegerField(choices=[(0, "User"), (1, "Organizations")]),
        ),
    ]
