# Generated by Django 5.2 on 2025-05-11 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seminar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='date',
            new_name='seminar_date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='participant_count',
        ),
        migrations.AddField(
            model_name='seminar',
            name='guest',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='seminars_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_seminars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
