# Generated by Django 5.2 on 2025-05-24 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_seminar_seminar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_seminars', to=settings.AUTH_USER_MODEL),
        ),
    ]
