# Generated by Django 5.2 on 2025-05-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_seminar_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
