# Generated by Django 5.2 on 2025-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_organizations_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='image',
        ),
        migrations.AddField(
            model_name='organizations',
            name='org_logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics_org/'),
        ),
    ]
