# Generated by Django 5.2 on 2025-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_organizations_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
