# Generated by Django 5.2 on 2025-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='is_open_for_volunteers',
            field=models.BooleanField(default=False),
        ),
    ]
