# Generated by Django 5.2 on 2025-06-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_orphan_donation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='orphan_profile_pics/'),
        ),
    ]
