# Generated by Django 5.2 on 2025-06-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_adoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donated_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='receiver_type',
            field=models.CharField(choices=[('orphan', 'Orphan'), ('organization', 'Organization')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='api.organizations'),
        ),
    ]
