from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import RegisterView, LoginView, approve_organization, pending_organization, OrganizationProfileView, SeminarListView, OrganizationListView, SeminarDeleteView, OrganizationVolunteersView, OpenVolunteerApplicationView, BlogListView, FetchOpenVolunteerApplicationsView, ApplyForVolunteeringView, OrganizationVolunteerApplicationsView, ApproveVolunteerApplicationView, DeclineVolunteerApplicationView, SeminarRegistrationView, SeminarDeregistrationView, SeminarRegistrationStatusView, UserProfileView, UserVolunteerApplicationsView, OrphanCreateView, OrphanCountView, OrphanListView, AdoptionRequestView, AdoptionCancelView, UserAdoptionRequestsView, OrganizationAdoptionRequestsView, ApproveAdoptionRequestView, RejectAdoptionRequestView, OrphanDonationView, PaymentProcessView, PaymentSuccessView, UserDonationsView, UserRegisteredSeminarsView, OrganizationDonationsView, OrganizationDirectDonationView, BlogReactionView, UserBlogReactionsView
from .models import get_username
from . import views

urlpatterns = [
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("login/", LoginView.as_view(), name='login'),
    path("register/", RegisterView.as_view(), name='register'),
    path("api/user/", get_username, name="get-username"),
    path("user/profile/", UserProfileView.as_view(), name="user-profile"),
    path("approve-organization/<int:user_id>/", approve_organization, name="approve-organization"),
    path("pending-organization/", pending_organization, name="pending-organization"),
    path("organizations/", OrganizationListView.as_view(), name="organization-list"),
    path("organization/profile/", OrganizationProfileView.as_view(), name="organization-profile"),
    path("seminars/", SeminarListView.as_view(), name="seminar-list-create"),
    path("seminars/<int:seminar_id>/", views.fetch_seminar_details, name="seminar-detail"),
    path("own-seminars/", views.fetch_own_seminar, name="fetch-own-seminars"),
    path("available-seminars/", views.fetch_available_seminars, name="fetch-available-seminars"),
    path('seminars/<int:seminar_id>/register/', SeminarRegistrationView.as_view(), name='seminar-registration'),
    path('seminars/<int:seminar_id>/deregister/', SeminarDeregistrationView.as_view(), name='seminar-deregistration'),
    path('seminars/<int:seminar_id>/is-registered/', SeminarRegistrationStatusView.as_view(), name='seminar-registration-status'),
    path('seminar-delete/<int:seminar_id>/', SeminarDeleteView.as_view(), name='seminar-delete'),
    path('organization/volunteers/', OrganizationVolunteersView.as_view(), name='organization-volunteers'),
    path('organization/seminars/<int:seminar_id>/open-volunteer/', OpenVolunteerApplicationView.as_view(), name='open-volunteer-application'),
    path('organization/seminars/', views.fetch_own_seminar, name='organization-seminars'),
    path('blogs/', BlogListView.as_view(), name='blog-list-view'),
    path('blogs/<int:blog_id>/react/', BlogReactionView.as_view(), name='blog-reaction'),
    path('blogs/user-reactions/', UserBlogReactionsView.as_view(), name='user-blog-reactions'),
    path('organization/volunteers/', OrganizationVolunteersView.as_view(), name='organization-volunteers'),
    path('volunteer/open-applications/', FetchOpenVolunteerApplicationsView.as_view(), name='open-volunteer-applications'),
    path('volunteer/apply/<int:seminar_id>/', ApplyForVolunteeringView.as_view(), name='apply-for-volunteer'),
    path('organization/volunteer-applications/', OrganizationVolunteerApplicationsView.as_view(), name='organization-volunteer-applications'),
    path('organization/volunteer-applications/<int:application_id>/approve/', ApproveVolunteerApplicationView.as_view(), name='approve-volunteer-application'),
    path('organization/volunteer-applications/<int:application_id>/decline/', DeclineVolunteerApplicationView.as_view(), name='decline-volunteer-application'),
    path('volunteer/my-applications/', UserVolunteerApplicationsView.as_view(), name='user-volunteer-applications'),
    path('organization/orphans/', OrphanCreateView.as_view(), name='orphan-create'),
    path('organization/orphans/count/', OrphanCountView.as_view(), name='orphan-count'),
    path('orphans/list/', OrphanListView.as_view(), name="orphan-list"),
    path('adoption/request/', AdoptionRequestView.as_view(), name='adoption-request'),
    path('adoption/cancel/<int:orphan_id>/', AdoptionCancelView.as_view(), name='adoption-cancel'),
    path('adoption/user-requests/', UserAdoptionRequestsView.as_view(), name='user-adoption-requests'),
    path('adoption/organization-requests/', OrganizationAdoptionRequestsView.as_view(), name='organization-adoption-requests'),
    path('adoption/approve/<int:adoption_id>/', ApproveAdoptionRequestView.as_view(), name='approve-adoption'),
    path('adoption/reject/<int:adoption_id>/', RejectAdoptionRequestView.as_view(), name='reject-adoption'),
    path('donations/orphan/', OrphanDonationView.as_view(), name='orphan-donation'),
    path('payment/process/<int:donation_id>/', PaymentProcessView.as_view(), name='payment-process'),
    path('payment/success/<int:donation_id>/', PaymentSuccessView.as_view(), name='payment-success'),
    path('donations/user/', UserDonationsView.as_view(), name='user-donations'),
    path('seminars/registered/', UserRegisteredSeminarsView.as_view(), name='user-registered-seminars'),
    # path('donations/status/<int:donation_id>/', DonationStatusView.as_view(), name='donation-status'),
    path('donations/organization/', OrganizationDirectDonationView.as_view(), name='organization-donation'),
]